run:
  timeout: 10m
  modules-download-mode: readonly
  go: '1.21'

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - gocritic
    - revive
  disable:
    - gosec  # We handle security scanning separately
    - funlen
    - gocognit
    - nestif
    - cyclop
    - gocyclo
    - lll
    - dupl

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
  gocritic:
    disabled-checks:
      - commentFormatting
      - ifElseChain
      - singleCaseSwitch
  errcheck:
    check-type-assertions: false
    check-blank: false
  misspell:
    locale: US
  govet:
    disable:
      - shadow
  staticcheck:
    checks: ["all"]

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - revive
        - gocritic
    # Exclude generated files
    - path: ".*\\.pb\\.go"
      linters:
        - all
    # Allow TODO comments
    - source: "TODO"
      linters:
        - godox
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: origin/main
