version: '3.8'

services:
  alloracli:
    build:
      context: .
      dockerfile: Dockerfile
    image: alloracli:latest
    container_name: alloracli
    environment:
      - ALLORA_CONFIG_PATH=/app/config
      - ALLORA_LOG_LEVEL=debug
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    networks:
      - allora-network
    depends_on:
      - prometheus
      - grafana
      - redis
    command: ["monitor", "--help"]

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: allora-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - allora-network

  # Grafana for dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: allora-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana:/etc/grafana/provisioning
    networks:
      - allora-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: allora-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - allora-network

  # Elasticsearch for log storage
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: allora-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - allora-network

  # Kibana for log visualization
  kibana:
    image: kibana:8.11.0
    container_name: allora-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - allora-network

  # Example cloud provider simulator
  localstack:
    image: localstack/localstack:latest
    container_name: allora-localstack
    environment:
      - SERVICES=s3,ec2,iam,lambda,dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - localstack_data:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - allora-network

volumes:
  prometheus_data:
  grafana_data:
  redis_data:
  elasticsearch_data:
  localstack_data:

networks:
  allora-network:
    driver: bridge
