name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Run tests
      run: go test ./...
    
    - name: Build binaries
      run: |
        mkdir -p dist
        
        # Linux
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o dist/allora-linux-amd64 ./cmd/allora
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o dist/allora-linux-arm64 ./cmd/allora
        
        # macOS
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o dist/allora-darwin-amd64 ./cmd/allora
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o dist/allora-darwin-arm64 ./cmd/allora
        
        # Windows
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o dist/allora-windows-amd64.exe ./cmd/allora
    
    - name: Create checksums
      run: |
        cd dist
        sha256sum * > checksums.txt
    
    - name: Generate changelog
      id: changelog
      run: |
        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        body: |
          ## What's Changed
          ${{ steps.changelog.outputs.CHANGELOG }}
          
          ## Installation
          
          Download the appropriate binary for your system:
          
          ### Linux
          ```bash
          curl -L https://github.com/AlloraAi/AlloraCLI/releases/download/${{ github.ref_name }}/allora-linux-amd64 -o allora
          chmod +x allora
          sudo mv allora /usr/local/bin/
          ```
          
          ### macOS
          ```bash
          curl -L https://github.com/AlloraAi/AlloraCLI/releases/download/${{ github.ref_name }}/allora-darwin-amd64 -o allora
          chmod +x allora
          sudo mv allora /usr/local/bin/
          ```
          
          ### Windows
          Download `allora-windows-amd64.exe` and add to your PATH.
        files: |
          dist/*
        draft: false
        prerelease: false
